application/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, HiddenField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = HiddenField("Content", validators=[DataRequired()], id="post_content")
    tags = StringField("Tags")
    submit = SubmitField("Post")

application/comments/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from application import db
from application.models import Comment, Post
from application.comments.forms import CommentForm

comments = Blueprint('comments', __name__)


@comments.route("/post/<int:post_id>/comments", methods=['GET', 'POST'])
@login_required
def new_comment(post_id):
    form = CommentForm()
    if request.method == 'POST':
        print(form.is_submitted(), form.validate())
        if form.validate_on_submit():
            comment = Comment(content=form.content.data, author=current_user, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
            flash('Your comment has been added!', 'success')
        else:
            flash('Your comment has not been added!', 'error')
            return redirect(url_for('posts.post', post_id=post_id))

    return redirect(url_for('posts.post', post_id=post_id))

application/main/routes.py
import readtime
from flask import render_template, request, Blueprint
from sqlalchemy import func, desc

from application.models import Post, Comment, Tag
from application import db
from application.posts.utils import listToString
from application.users.utils import truncate_html

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    subquery = db.session.query(Comment.post_id, func.count(Comment.post_id).label('count')).group_by(Comment.post_id).subquery()
    results = db.session.query(Post, subquery.c.count).outerjoin(subquery, subquery.c.post_id == Post.id).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)

    for result in results.items:
        reading_time = readtime.of_html(result[0].content)
        result[0].reading_time = reading_time
        result[0].truncated_content = truncate_html(result[0].content, 500)
        tags = listToString(Tag.query.filter_by(post_id=result[0].id).all()).split(",")

        result[0].tags_list = tags

    most_viewed_post = Post.query.order_by(Post.views.desc()).first()
    most_popular_tags = db.session.query(Tag.content, func.count(Tag.content).label('count')).group_by(Tag.content).order_by(desc('count')).limit(3).all()

    return render_template('home.html', results=results, most_viewed_post=most_viewed_post, most_popular_tags=most_popular_tags)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

application/posts/routes.py
import json

import readtime
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from sqlalchemy import func

from application import db
from application.models import Post, Comment, User, Vote, Tag
from application.posts.forms import PostForm
from application.comments.forms import CommentForm
from application.posts.utils import listToString, stringToTagList
from application.users.utils import truncate_html

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():

    if current_user.id != 1:
        # allow only admin
        abort(403, description='Not allowed')

    form = PostForm()
    if form.validate_on_submit():
        tag_list = stringToTagList(form.tags.data)
        print(tag_list)
        post = Post(title=form.title.data, content=form.content.data, author=current_user, tags=tag_list)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    user = current_user
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    comment = Comment.query.filter_by(post_id=post_id).all()
    comment_count = Comment.query.filter_by(post_id=post.id).count()
    reading_time = readtime.of_html(post.content)

    post.views += 1
    db.session.commit()

    post_likes = Vote.query.filter_by(status=1, post_id=post_id).count()
    post_dislikes = Vote.query.filter_by(status=0, post_id=post_id).count()

    tags = listToString(Tag.query.filter_by(post_id=post_id).all()).split(",")

    if current_user.is_authenticated:
        vote = Vote.query.filter_by(user_id=user.id, post_id=post_id).first()
        return render_template('post.html', vote=vote, title=post.title, post=post, form=form, comment=comment, comment_count=comment_count, reading_time=reading_time, post_likes=post_likes, post_dislikes=post_dislikes, tags=tags)
    else:
        return render_template('post.html', title=post.title, post=post, form=form, comment=comment, comment_count=comment_count, reading_time=reading_time, post_likes=post_likes, post_dislikes=post_dislikes, tags=tags)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):

    if current_user.id != 1:
        # allow only admin
        abort(403, description='Not allowed')

    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        # delete existing post's tags
        Tag.query.filter(Tag.post_id == post_id).delete()
        post.title = form.title.data
        post.content = form.content.data
        # add any tags from form
        post.tags = stringToTagList(form.tags.data)
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        tag_list = post.tags
        tags = listToString(tag_list)
        form.title.data = post.title
        form.content.data = post.content
        form.tags.data = tags
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):

    if current_user.id != 1:
        # allow only admin
        abort(403, description='Not allowed')

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/post/<int:post_id>/vote", methods=['POST'])
@login_required
def vote_post(post_id):

    bodyJson = request.get_data()
    body = json.loads(bodyJson)
    response = body['status']
    user = current_user
    exists = Vote.query.filter_by(user_id=user.id, post_id=post_id).first()

    if exists is None:
        new_vote = Vote(status=response, user_id=user.id, post_id=post_id)
        db.session.add(new_vote)
        db.session.commit()
    else:
        if exists.status is True:
            if response is True:
                vote = Vote.query.filter_by(user_id=user.id, post_id=post_id).first()
                db.session.delete(vote)
                db.session.commit()
            else:
                vote = Vote.query.filter_by(user_id=user.id, post_id=post_id).first()
                new_vote = Vote(status=response, user_id=user.id, post_id=post_id)
                db.session.delete(vote)
                db.session.add(new_vote)
                db.session.commit()
        else:
            if response is True:
                vote = Vote.query.filter_by(user_id=user.id, post_id=post_id).first()
                new_vote = Vote(status=response, user_id=user.id, post_id=post_id)
                db.session.delete(vote)
                db.session.add(new_vote)
                db.session.commit()
            else:
                vote = Vote.query.filter_by(user_id=user.id, post_id=post_id).first()
                db.session.delete(vote)
                db.session.commit()

    return {"message": "OK"}, 200


@posts.route("/post/tag/<content>")
def tagged_posts(content):

    page = request.args.get('page', 1, type=int)

    subquery = db.session.query(Comment.post_id, func.count(Comment.post_id).label('count')).group_by(
        Comment.post_id).subquery()
    results = db.session.query(Post, subquery.c.count).outerjoin(subquery, subquery.c.post_id == Post.id).join(
        Tag).filter(Tag.content == content).order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=5)

    for result in results.items:
        reading_time = readtime.of_html(result[0].content)
        result[0].reading_time = reading_time
        result[0].truncated_content = truncate_html(result[0].content, 500)
        tags = listToString(Tag.query.filter_by(post_id=result[0].id).all()).split(",")
        result[0].tags_list = tags


    return render_template('tagged_posts.html', results=results, reading_time=reading_time, tags=tags)


@posts.route("/post/<int:post_id>/counters")
def count_votes(post_id):

    post_likes = Vote.query.filter_by(status=1, post_id=post_id).count()
    post_dislikes = Vote.query.filter_by(status=0, post_id=post_id).count()

    return {"likes": post_likes, "dislikes": post_dislikes}, 200

application/users/routes.py
import readtime
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import func

from application import db, bcrypt
from application.models import User, Post, Tag, Comment
from application.posts.utils import listToString
from application.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm)
from application.users.utils import save_picture, truncate_html

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.bio.data = current_user.bio
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()

    subquery = db.session.query(Comment.post_id, func.count(Comment.post_id).label('count'))\
        .group_by(Comment.post_id)\
        .subquery()

    results = db.session.query(Post, subquery.c.count)\
        .filter_by(author=user)\
        .outerjoin(subquery, subquery.c.post_id == Post.id)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)

    for result in results.items:
        reading_time = readtime.of_html(result[0].content)
        result[0].reading_time = reading_time
        result[0].truncated_content = truncate_html(result[0].content, 500)
        tags = listToString(Tag.query.filter_by(post_id=result[0].id).all()).split(",")
        result[0].tags_list = tags

    return render_template('user_posts.html', results=results, user=user, reading_time=reading_time, tags=tags)

application/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <div class="fs-4">
    <p>Hello!</p>

    <p>This post was created to help new developers learn more about key concepts of programming.</p>
    <p>I mainly post articles about things that I found important when I first started my journey into programming or things that I want to learn/improve upon.</p>
    <p>Cheers,</p>
        <p>Georgia</p>
    </div>
{% endblock content %}

application/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.css"
          integrity="sha512-5m1IeUDKtuFGvfgz32VVD0Jd/ySGX7xdLxhqemTmThxHdgqlgPdupWoSN8ThtUSLpAGBvA8DY2oO7jJCrGdxoA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link href="https://pagecdn.io/lib/easyfonts/pushster.css" rel="stylesheet" />

    {% if title %}
    <title>Coding Secrets - {{ title }}</title>
    {% else %}
    <title>Coding Secrets</title>
    {% endif %}
</head>
<body class="d-flex flex-column min-vh-100">
<header class="site-header fixed-top">
    <div class="header-brand d-none d-md-block"><a href="/">Coding Secrets</a>
    </div>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand d-md-none" href="/">Coding Secrets</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('main.about') }}">About</a>
                    </li>

                    {% if current_user.is_authenticated %}
                    {% if current_user.id == 1 %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('posts.new_post') }}">New Post</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('users.account') }}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('users.logout') }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('users.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('users.register') }}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>
<button type="button" class="btn btn-primary btn-floating btn-md rounded-circle" id="btn-back-to-top">
  <i class="fas fa-arrow-up"></i>
</button>
<footer class="mt-auto">
    <div class="text-center p-3">
        © 2021 Copyright: Coding Secrets
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.js"
        integrity="sha512-2RLMQRNr+D47nbLnsbEqtEmgKy67OSCpWJjJM394czt99xj3jJJJBQ43K7lJpfYAYtvekeyzqfZTx2mqoDh7vg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="../static/script.js"></script>
</body>
</html>

application/templates/post.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="card mb-4">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="me-2">
                            <img class="rounded-circle" height="50" width="50"
                                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
                                 alt="">
                        </div>
                        <div class="ms-2">
                            <div class="h5 m-0">
                                <a class="me-2 author"
                                   href="{{ url_for('users.user_posts', username=post.author.username) }}">{{
                                    post.author.username }}</a>
                            </div>
                            <div class="h7 text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</div>
                        </div>
                    </div>
                    <div class="text-muted"><i class="far fa-clock"> {{ reading_time }} </i></div>
                </div>
                {% if post.author == current_user %}
                <hr class="mt-2 mb-2">
                <div>
                    <a class="btn btn-primary btn-sm mt-1 mb-1"
                       href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
                            data-bs-target="#deleteModal"> Delete
                    </button>
                </div>
                {% endif %}
            </div>
            <div class="card-body">
                <a class="card-link" href="{{ url_for('posts.post', post_id=post.id) }}">
                    <h5 class="card-title">{{ post.title }}</h5>
                </a>
                <p class="card-text">{{ post.content | safe }}</p>
                {% for tag in tags %}
                {% if tag|length %}
                <span class="badge bg-primary"><i class="fas fa-tags"></i> {{ tag }}</span>
                {% endif %}
                {% endfor %}
            </div>
            <div class="card-footer d-flex justify-content-between align-content-center">
                <div class="align-items-center d-flex">
                    <a href="#" class="facebook-btn me-1">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="#" class="twitter-btn me-1">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="#" class="linkedin-btn me-1">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="#" class="whatsapp-btn">
                        <i class="fab fa-whatsapp"></i>
                    </a>
                </div>
                <div>
                    <button id="dislike"
                            class="btn btn-light vote {{ 'is-voted' if vote is defined and vote.status == False }}">
                        <i class="fas fa-thumbs-down"></i>
                        <span class="badge bg-secondary">{{ post_dislikes }}</span>
                    </button>
                    <button id="like" class="btn btn-light vote {{ 'is-voted' if vote is defined and vote.status }}">
                        <i class="fas fa-thumbs-up"></i>
                        <span class="badge bg-sm bg-secondary">{{ post_likes }}</span>
                    </button>
                </div>
            </div>
        </div>

        <div class="card mb-4">
            <form method="POST" action="{{ url_for('comments.new_comment', post_id=post.id) }}">
                <div class="card-header">
                    Leave a comment!
                </div>
                <div class="card-body">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group">
                            {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                </div>
                <div class="card-footer">
                    <div class="form-group mt-1">
                        {{ form.submit(class="btn btn-sm btn-primary") }}
                    </div>
                </div>
            </form>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                All comments ({{ comment_count }})
            </div>
            <div class="card-body">
                {% if comment.post_id == post_id %}
                {% for comment in comment %}
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <small class="text-muted">{{ comment.author.username }} {{
                                comment.date_posted.strftime('%Y-%m-%d')
                                }}</small>
                        </div>
                        <p class="article-content">{{ comment.content }}</p>
                    </div>
                </article>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-4">
        {% if post.author.bio %}
        <div class="card mb-4">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="me-2">
                            <img class="rounded-circle" height="50" width="50"
                                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
                                 alt="">
                        </div>
                        <div class="ms-2">
                            <div class="h5 m-0">
                                <a class="me-2 author"
                                   href="{{ url_for('users.user_posts', username=post.author.username) }}">{{
                                    post.author.username }}</a>
                            </div>
                            <div class="h7 text-muted">User bio</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="media-body">
                    <p class="article-content">{{ post.author.bio }}</p>
                </div>
            </div>
            {% endif %}
        </div>

    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this post?
            </div>
            <div class="modal-footer">
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                    <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </form>

            </div>
        </div>
    </div>
</div>

<script>
(function () {

    var updateCounters = function() {

        const url = "{{ url_for('posts.count_votes', post_id=post.id) }}"
        fetch(url, {
          credentials: 'include'
        }).then(response => response.json())
        .then(response => {
            console.log(response);
            document.getElementById("like").getElementsByTagName("span")[0].innerText = response.likes
            document.getElementById("dislike").getElementsByTagName("span")[0].innerText = response.dislikes
        }).catch((error) => {
            console.error('Error:', error);
        });
    };

    document.getElementById("like").addEventListener("click", () => {

        {% if current_user.is_authenticated %}
        const url = "{{ url_for('posts.vote_post', post_id=post.id) }}"
        data = {
            status: true
        };

        fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          credentials: 'include',
          body: JSON.stringify(data)
        }).then(response => {
            console.log(response);
            updateCounters();
            document.getElementById("dislike").classList.remove('is-voted');

            if (document.getElementById("like").classList.contains('is-voted')) {
                document.getElementById("like").classList.remove('is-voted');
            } else {
                document.getElementById("like").classList.add('is-voted');
            }
        }).catch((error) => {
            console.error('Error:', error);
        });
        {% else %}
        alert("Please log in first!");
        {% endif %}
    });

    document.getElementById("dislike").addEventListener("click", () => {

        {% if current_user.is_authenticated %}
        const url = "{{ url_for('posts.vote_post', post_id=post.id) }}"
        data = {
            status: false
        };

        fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          credentials: 'include',
          body: JSON.stringify(data)
        }).then(response => {
            console.log(response);
            updateCounters();
            document.getElementById("like").classList.remove('is-voted');

            if (document.getElementById("dislike").classList.contains('is-voted')) {
                document.getElementById("dislike").classList.remove('is-voted');
            } else {
                document.getElementById("dislike").classList.add('is-voted');
            }

        }).catch((error) => {
            console.error('Error:', error);
        });

        {% else %}
        alert("Please log in first!");
        {% endif %}
    });


})();


</script>
{% endblock content %}

application/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}

                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
</div>
{% endblock content %}